### ISSUE TITLE
Groupの新規作成機能

### ISSUE THREAD

**Issue by YutaroObuchi** [YutaroObuchi/kajino#4]
* groupテーブルの作成
* group作成機能の実装

**Comment by YutaroObuchi** [comment]
# コントローラーの作成について

## 実現したいこと
* コントローラーの作成

## 現状発生している問題・エラーメッセージ


```
obuchiyutaro@oofuchiyuutarounoMacBook-Pro kajino % docker-compose run web rails g controller group
Creating kajino_web_run ... done
/app/vendor/bundler/ruby/2.7.0/gems/rb-inotify-0.10.1/lib/rb-inotify/native.rb:1:in `require': cannot load such file -- ffi (LoadError)
	from /app/vendor/bundler/ruby/2.7.0/gems/rb-inotify-0.10.1/lib/rb-inotify/native.rb:1:in `<top (required)>'
	from /app/vendor/bundler/ruby/2.7.0/gems/rb-inotify-0.10.1/lib/rb-inotify.rb:2:in `require'
	from /app/vendor/bundler/ruby/2.7.0/gems/rb-inotify-0.10.1/lib/rb-inotify.rb:2:in `<top (required)>'
	from /app/vendor/bundler/ruby/2.7.0/gems/listen-3.5.1/lib/listen/adapter/linux.rb:33:in `require'
	from /app/vendor/bundler/ruby/2.7.0/gems/listen-3.5.1/lib/listen/adapter/linux.rb:33:in `_configure'
	from /app/vendor/bundler/ruby/2.7.0/gems/listen-3.5.1/lib/listen/adapter/base.rb:47:in `block in configure'
	from /app/vendor/bundler/ruby/2.7.0/gems/listen-3.5.1/lib/listen/adapter/base.rb:42:in `each'
	from /app/vendor/bundler/ruby/2.7.0/gems/listen-3.5.1/lib/listen/adapter/base.rb:42:in `configure'
	from /app/vendor/bundler/ruby/2.7.0/gems/listen-3.5.1/lib/listen/adapter/base.rb:66:in `start'
	from /usr/local/lib/ruby/2.7.0/forwardable.rb:235:in `start'
	from /app/vendor/bundler/ruby/2.7.0/gems/listen-3.5.1/lib/listen/listener.rb:71:in `block in <class:Listener>'
	from /app/vendor/bundler/ruby/2.7.0/gems/listen-3.5.1/lib/listen/fsm.rb:124:in `instance_eval'
	from /app/vendor/bundler/ruby/2.7.0/gems/listen-3.5.1/lib/listen/fsm.rb:124:in `call'
	from /app/vendor/bundler/ruby/2.7.0/gems/listen-3.5.1/lib/listen/fsm.rb:105:in `transition_with_callbacks!'
	from /app/vendor/bundler/ruby/2.7.0/gems/listen-3.5.1/lib/listen/fsm.rb:72:in `transition'
	from /app/vendor/bundler/ruby/2.7.0/gems/listen-3.5.1/lib/listen/listener.rb:92:in `start'
	from /app/vendor/bundler/ruby/2.7.0/gems/spring-watcher-listen-2.0.1/lib/spring/watcher/listen.rb:27:in `start'
	from /app/vendor/bundler/ruby/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:80:in `start_watcher'
	from /app/vendor/bundler/ruby/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:89:in `preload'
	from /app/vendor/bundler/ruby/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
	from /app/vendor/bundler/ruby/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
	from /app/vendor/bundler/ruby/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
	from /app/vendor/bundler/ruby/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
	from /app/vendor/bundler/ruby/2.7.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from -e:1:in `<main>'
ERROR: 1
```

## 該当のソースコード

`config/application.rb`
```
require_relative 'boot'

require "rails"
# Pick the frameworks you want:
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
require "active_storage/engine"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_mailbox/engine"
require "action_text/engine"
require "action_view/railtie"
require "action_cable/engine"
require "sprockets/railtie"
# require "rails/test_unit/railtie"

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module App
  class Application < Rails::Application
    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 6.0

    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration can go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded after loading
    # the framework and any gems in your application.

    # Don't generate system test files.
    config.generators do |g|
      g.skip_routes true
      g.assets false
      g.helper false
      g.test_framework false
    end
  end
end
```

## エラーから考えられる原因
dockerの導入時に、何かしらの不備があった？


## 試したこと

* `module App`の名前変更
* `gem ffi `の導入
* `require rails`以下をコメントアウトし、`require 'rails/all'`に変更した

## 参考にした記事
https://stackoverflow.com/questions/29092233/how-to-resolve-loaderror-cannot-load-such-file-ffi-c

よろしくお願いします。

**Comment by MrFuku** [comment]
@YutaroObuchi 
`docker-compose run web bash(もしくはsh)`でコンテナ内に入り、ffiがインストールできているか確認してみてください。
インストールできていなければそのまま（コンテナ内で）bundleインストールし、`rails g`でコントローラー作成を試してみてください

**Comment by YutaroObuchi** [comment]
コメントありがとうございます！

>ffiがインストールできているか確認してみてください
こちら確認したところ問題なくインストールできているようでした。
(再度rails g controllerを試しましたが結果も変わらず)

`画像`
[![Image from Gyazo](https://i.gyazo.com/c04728076e41b6198967cfbae76d99bf.png)](https://gyazo.com/c04728076e41b6198967cfbae76d99bf)


当方の仮説としては、`ruby2.7.0`を使っていることでエラーが出ているのではないかと思いました。
理由としては下記になります。

**① サーバー立ち上げ時にもffi関連のエラーが出ている**
```
/app/vendor/bundler/ruby/2.7.0/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': cannot load such file -- /app/vendor/bundler/ruby/2.7.0/gems/ffi-1.15.0/lib/ffi.rb (LoadError)
```
**② 2.6系でサーバーを立ち上げ or コントローラ作成を試すと成功する**

**③ `require`できないと言われている`kernel_require.rb`のコードは2.7系と2.6系で差がない**

```
module Kernel
  module_function # rubocop:disable Style/ModuleFunction

  alias_method(:require_without_bootsnap, :require)

  # Note that require registers to $LOADED_FEATURES while load does not.
  def require_with_bootsnap_lfi(path, resolved = nil)
    Bootsnap::LoadPathCache.loaded_features_index.register(path, resolved) do
      require_without_bootsnap(resolved || path)
    end
  end

〜
end
```

コントーローラー作成とサーバー起動の問題は本来切り分けるべきかとは思いますが、関係していそうなため報告させていただきました。引き続きよろしくお願いします。

**Comment by MrFuku** [comment]
@YutaroObuchi 
僕のところでは作成できましたね。おそらくdockerの使い方の問題かなと思いました。
作業中のコードをpushすることはできますか？

ちなみに僕のローカルではこんな感じで動きました
```bash
❯ docker-compose run web rails g controller group
Starting kajino_db_1 ... done
Running via Spring preloader in process 70
      create  app/controllers/group_controller.rb
      invoke  erb
      create    app/views/group
      invoke  rspec
      create    spec/requests/group_spec.rb
      invoke  helper
      create    app/helpers/group_helper.rb
      invoke    rspec
      create      spec/helpers/group_helper_spec.rb
      invoke  assets
      invoke    scss
      create      app/assets/stylesheets/group.scss

fuku in think in kajino on  main [?] via ⬢ v15.11.0 via 💎 v2.7.2 on ☁️  (ap-northeast-1) took 10s 
❯ git log
commit a469f7b1d4b0017f84e17ffd1e2c40c03034675f (HEAD -> main, origin/main, origin/HEAD)
Merge: accfff9 68cc5bf
Author: YutaroObuchi <76048814+YutaroObuchi@users.noreply.github.com>
Date:   Mon May 3 13:30:02 2021 +0900

    Merge pull request #18 from YutaroObuchi/04_environment_setting
    
    04 environment setting
```

**Comment by MrFuku** [comment]
多分`bundle install`あたりが怪しいかなと思います
`.bundle/config`でgemのインストール先を指定していますか？
もしかするとそれが原因じゃないかなと思いました。

`.bundle/config`を削除（gemインストール先のディレクトリも削除）して、`docker-compose build --no-cache`でdockerイメージを作り直せばいけるんじゃないかなーと思います。

**Comment by MrFuku** [comment]
ちなみにrailsもdocker化した経緯ってなんですか？
DBのdocker化は聞いていたのですが、railsまでとは思っていなくて

学習コストの問題もあるのでDBのみでも良いのかなーと思ったので聞いてみました

**Comment by YutaroObuchi** [comment]
コメントありがとうございます！
まず結論からお伝えすると、サーバーの起動及びコントローラーの作成に関しては成功しました。


> 多分bundle installあたりが怪しいかなと思います
> .bundle/configでgemのインストール先を指定していますか？
> もしかするとそれが原因じゃないかなと思いました。

こちらご指摘の通り、`.bundle/config`でファイルが確認できたため削除いたしました。

[![Image from Gyazo](https://i.gyazo.com/ef426931853fb7ee7152c1a58b61b0bd.png)](https://gyazo.com/ef426931853fb7ee7152c1a58b61b0bd)

※ ファイル内では`vendor/bundle`がインストール先として指定されておりました。

>.bundle/configを削除（gemインストール先のディレクトリも削除）して、docker-compose build --no-cacheでdockerイメー>ジを作り直せばいけるんじゃないかなーと思います。

①アプリ内で`vendor/bundle`を削除後
②`docker-compose build --no-cacheでdocker`を実行
③ 再度`docker-compose run web bundle install`を実行
③ `vendor`下に再度`bundle`が作成される
④ サーバーの起動 及び コントローラーの作成が成功

と行った手順で解決することができました。


>ちなみにrailsもdocker化した経緯ってなんですか？
>DBのdocker化は聞いていたのですが、railsまでとは思っていなくて
>学習コストの問題もあるのでDBのみでも良いのかなーと思ったので聞いてみました

こちら当方の知識不足で、DBのdocker化 =  railsのdocker化が必要と誤認しておりました。
学習コストの問題があるということなので、切替を前提として、調べながら実装していければと思います。
引き続きよろしくお願いします！

**Comment by YutaroObuchi** [comment]
## mysqlのみdocker化させる件につきまして

現在mysqlのみdocker化するよう実装を進めておりますが、実装にむけて質問させていただいても良いでしょうか？

### お聞きしたいこと

① DBのみのdooker化の手順として誤りはないか？
　(参考記事はrailsもdooker化しているため、どこかで齟齬が発生しているなど)

② 手順として問題ないようでしたら、どの部分で引っかかっておりDBが構築できないのか？
→Dockerfile,docker-compose.ymlあたりのコードが原因なのではないかと思っているのですが解決できず

### 現状の実装手順 (別アプリとしてテスト作成しております)

①ファイルの生成
```
touch {Dockerfile,docker-compose.yml,entrypoint.sh,.env}
```

②ファイルの編集

`Dockerfile`
```
FROM ruby:2.7.2

ENV LANG C.UTF-8
ENV APP_ROOT /app

# install required libraries
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
  apt-get update -qq && \
  apt-get install -y --no-install-recommends \
  build-essential \
  nodejs \
  yarn && \
  apt-get clean && \
  rm --recursive --force /var/lib/apt/lists/*

# create working directory
RUN mkdir $APP_ROOT
WORKDIR $APP_ROOT

# bundle install
COPY Gemfile $APP_ROOT/Gemfile
COPY Gemfile.lock $APP_ROOT/Gemfile.lock
RUN bundle install --jobs 4 --retry 3

# create app in container
COPY . $APP_ROOT

# script to be executed every time the container starts
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

# Start the main process
CMD ["rails", "server", "-b", "0.0.0.0"]

```

`docker-compose.yml`
```
version: '3.7'
services:
  db:
    image: mysql:8.0.20
    volumes:
      - mysql:/var/lib/mysql:delegated
    ports:
      - '3307:3306'
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    env_file: .env
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle:delegated
      - node_modules:/app/node_modules
      - tmp-data:/app/tmp/sockets

volumes:
  mysql:
  bundle:
  node_modules:
  tmp-data:
```

`.env`
```
MYSQL_ROOT_PASSWORD=password
TZ=Japan
```
`entrypoint.sh`
```
#!/bin/bash
set -e

# Remove a potentially pre-existing server.pid for Rails.
rm -f /myapp/tmp/pids/server.pid

# Then exec the container's main process (what's set as CMD in the Dockerfile).
exec "$@"
```

③ rails new でアプリ作成
```
rails _6.0.3.4_ new pakawaka --database=mysql --skip-test
```

④ database.ymlの編集

```
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USERNAME') { 'root' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { 'password' } %>
  host: <%= ENV.fetch('MYSQL_HOST') { 'db' } %>

development:
  <<: *default
  database: pakawaka_development

test:
  <<: *default
  database: pakawaka_test

production:
  <<: *default
  database: pakawaka_production
  username: pakawaka
  password: pakawakapakawaka
```
⑤ Dockerイメージをビルドし、DB作成
```
docker-compose build
docker-compose run web bin/rails db:create    ← ここでエラーが発生
```
[![Image from Gyazo](https://i.gyazo.com/d64bfe1c43e6f1445114cab755a756b8.png)](https://gyazo.com/d64bfe1c43e6f1445114cab755a756b8)

⑥ サーバー立ち上げ(当然できず)
```
docker-compose up
```
[![Image from Gyazo](https://i.gyazo.com/1ab284519b3a652460cb71c41395bda6.png)](https://gyazo.com/1ab284519b3a652460cb71c41395bda6)

[参考サイト](https://zenn.dev/shima_zu/articles/docker_on_rails6_mysql8)

お手数おかけしますが引き続きよろしくお願いします！
